# Generated by Django 3.1.2 on 2020-10-31 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kisan', '0002_auto_20201031_1247'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Things',
            new_name='Thing',
        ),
    ]
