# Generated by Django 3.1.2 on 2020-10-31 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kisan', '0004_auto_20201031_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='image',
            field=models.ImageField(default='', upload_to='static/images'),
        ),
    ]
