# Generated by Django 3.1.2 on 2020-10-31 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kisan', '0005_thing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='category',
            field=models.CharField(default='farming', max_length=100),
        ),
    ]
