# Generated by Django 3.1.2 on 2020-10-31 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kisan', '0008_auto_20201031_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='category',
            field=models.CharField(choices=[('Essentials', 'Essentials'), ('Green Vegetables', 'Green Vegetables'), ("Today's Special", "Today's Special")], default='Essentials', max_length=20),
        ),
    ]
