# Generated by Django 3.1.2 on 2020-10-31 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kisan', '0009_auto_20201031_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='detail_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('vege_ingo', models.CharField(max_length=100)),
            ],
        ),
    ]
