# Generated by Django 3.1.2 on 2020-10-31 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kisan', '0010_detail_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail_item',
            old_name='vege_ingo',
            new_name='vege_info',
        ),
    ]
