# Generated by Django 3.1.2 on 2020-10-31 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kisan', '0011_auto_20201101_0014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail_item',
            old_name='vege_info',
            new_name='vege',
        ),
    ]
