# Generated by Django 3.1.2 on 2020-10-31 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kisan', '0012_auto_20201101_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail_item',
            name='price',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
