# Generated by Django 3.1.2 on 2020-10-31 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kisan', '0013_detail_item_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='thing',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='thing',
            name='price',
            field=models.IntegerField(),
        ),
    ]
